config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  get 'new_admin' => 'experiences#new_admin'

  resources :experiences, only: [:index, :new, :create, :show]

  namespace :account do
    resources :experiences
  end

  # namespace :admin do
  #   resources :experiences
  # end

end

app/models/experience.rb
class Experience < ActiveRecord::Base

  # Associations
  belongs_to :user

  has_many :children_experiences, class_name: "Experience",
                                  foreign_key: "parent_experience_id"
  belongs_to :parent_experience, class_name: "Experience"

  has_many :relayed_experiences, class_name: "Experience",
                                  foreign_key: "initial_experience_id"
  belongs_to :initial_experience, class_name: "Experience"

  # Validations
  validates :title, :user, :category, presence: true
  validates :title, length: { minimum:3}

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
  # validates :picture, presence: true

  # Create global variable
  CATEGORIES = [
    'Creative',
    'Duo',
    'Family',
    'Foodies',
    'Novels',
    'Sports',
    'Sweetlife',
    'Travels',
    'Trendy'
  ]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :experiences

  def name
    email
  end

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/account/experiences_controller.rb
module Account
  class ExperiencesController < ApplicationController

    def index
      @experience = Experience.where(user: current_user)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @experiences = Experience.all
    @experience = @experiences.sample
  end

  def show
    @experience = Experience.find(params[:id])
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.save
      redirect_to experience_path(@experience)
    else
      render :new
    end
  end

  private

  def experience_params
    params.require(:experience).permit(:title, :category, :picture, :description, :address, :start_date, :end_date, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:home, :experiences_generator]
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= simple_form_for @experience, defaults: {label:false} do |f| %>
  <%= f.input :title,
              placeholder: "Faire un road trip en combi..." %>
  <%= f.input :category,
              as: :select,
              collection: Experience::CATEGORIES,
              prompt: "Choisissez une catégorie" %>
  <%= f.input :picture %>
  <%= f.input :description,
              label: false,
              as: :text,
              placeholder: "Description" %>
  <%= f.input :address,
              label: false,
              placeholder: "Adresse" %>
  <%= f.input :start_date,
              label: false,
              placeholder: "Début",
              as: :string,
              input_html: {class: "datetime date-inline"} %>
  <%= f.input :end_date,
              label: false,
              placeholder: "Fin",
              as: :string,
              input_html: {class: "datetime date-inline"} %>
  <%= f.input :status,
              label: false,
              collection: [["A vivre", false], ["S'en souvenir",true]],
              as: :radio_buttons,
              item_wrapper_class: "inline white",
              checked: false %>
  <%= f.button :submit, "Créez", class: "ghost-btn ghost-btn-white" %>
<% end %>

app/views/experiences/_form_admin.html.erb
<%= simple_form_for experience, defaults: {label:false} do |f| %>
  <%= f.input :title,
              placeholder: "Faire un road trip en combi..." %>
  <%= f.input :category,
              as: :select,
              collection: Experience::CATEGORIES,
              prompt: "Choisissez une catégorie" %>
  <%= f.input :picture %>
  <%= f.input :user,
              placeholder: "Inspiré par"
  %>
  <%= f.button :submit, "Créez", class: "ghost-btn ghost-btn-white" %>
<% end %>

app/views/experiences/index.html.erb
<%= render 'shared/card', experience: @experience %>

<%= render 'shared/selection_bar' %>

app/views/experiences/new.html.erb
<div class="bg bg-bridge padded text-center">
  <h2>Créer une nouvelle expérience</h2>
  <div class="padded-hor-10">
    <%= render "shared/form" %>
  </div>
</div>

app/views/experiences/new_admin.html.erb
<div class="bg padded text-center">
  <h2>Créer une nouvelle expérience</h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
        <div class="padded-10">
          <%= render 'form_admin', experience: @experience %>
        </div>
      </div>
    </div>
    <div class="row">
        <%= render 'shared/card_admin', experience: @last_experience %>
    </div>
  </div>
</div>

app/views/experiences/show.html.erb
<%= render 'shared/card', experience: @experience %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WOom, générateur d'expériences</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8"></meta>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/topbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footbar' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="padding-bottom-70 text-center">
  <div class="home-banner bg-intro">
    <span class="home-banner-shadow"></span>
    <div class="home-banner-content">
      <h1>Vivez vos expériences</h1>
    </div>
    <%= link_to "générateurs d'idées", experiences_path, class: "ghost-btn ghost-btn-white" %>
  </div>
  <div class="text-banner text-center">
    <p>Qu'allez-vous vivre ce mois-ci?</p>
  </div>
  <div class="category-banner bg-foodie">
    <div class="category-banner-content">
      <h2>Foodie</h2>
    </div>
    <span class="category-banner-shadow"></span>
  </div>
  <div class="category-banner bg-sport">
    <div class="category-banner-content">
      <h2>Sport</h2>
    </div>
    <span class="category-banner-shadow"></span>
  </div>
  <div class="category-banner bg-sweetlife">
    <div class="category-banner-content">
      <h2>Sweetlife</h2>
    </div>
    <span class="category-banner-shadow"></span>
  </div>
  <div class="category-banner bg-evasion">
    <div class="category-banner-content">
      <h2>Voyage</h2>
    </div>
    <span class="category-banner-shadow"></span>
  </div>
  <div class="category-banner bg-spectacle">
    <div class="category-banner-content">
      <h2>Spectacle</h2>
    </div>
    <span class="category-banner-shadow"></span>
  </div>
  <div class="text-banner text-center">
    <p>Créer vos expériences personnelles</p>
    <%= link_to "Créer", new_experience_path, class: "ghost-btn ghost-btn-grey" %>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card" style="background-image: url(<%= experience.picture.url(:medium)%>);">
  <div class="card-space"></div>
  <span class="card-category bg-<%= experience.category.downcase %>">
    <%= experience.category.capitalize %>
  </span>
  <div class="card-shadow"></div>
  <%= link_to experiences_path() do %>
    <div class="card-content">
      <h1><%= experience.title.capitalize %></h1>
      <p>
        inspiré par <%= experience.user.first_name %>
        <% if experience.user.picture %>
          <%= image_tag experience.user.picture, class: "avatar" %>
        <% end %>
      </p>
    </div>
  <% end %>
</div>

app/views/shared/_card_admin.html.erb
<div class="card-admin" style="background-image: url(<%= experience.picture.url(:medium)%>);">
  <%= image_tag 'Woom_logo_white.png' , class: "card-admin-logo" %>
  <span class="card-admin-category bg-<%= experience.category.downcase %>">
    <%= experience.category.capitalize %>
  </span>
  <div class="card-admin-shadow"></div>
  <%= link_to admin_experience_path(experience) do %>
    <div class="card-admin-content">
      <h1><%= experience.title.capitalize %></h1>
      <%= link_to admin_user_path(experience.user) do %>
        <p>
          inspiré par <%= experience.user.first_name %>
          <% if experience.user.picture %>
            <%= image_tag experience.user.picture, class: "avatar" %>
          <% end %>
        </p>
      <% end %>
    </div>
  <% end %>
  <div class="card-admin-hashtag">#WOom<%= experience.category.capitalize%></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footbar.html.erb
<div class="footbar bar-fixed">
  <div class="bar-container bar-container-white">
    <%= link_to experiences_path, {class: "bar-link"} do %>
      <div class="icon-btn">
        <%= image_tag "idea.png", {class: "small-icon"} %>
        <div class="icon-btn-text small-text">Trouver des idées</div>
      </div>
    <% end %>
    <%= link_to account_experiences_path, {class: "bar-link"} do %>
      <div class="icon-btn">
        <%= image_tag "moi.png", {class: "small-icon"} %>
        <div class="icon-btn-text small-text">Moi</div>
      </div>
    <% end %>
    <%= link_to new_experience_path, {class: "bar-link"} do %>
      <div class="icon-btn">
        <%= image_tag "create.png", {class: "small-icon"} %>
        <div class="icon-btn-text small-text">Créer une expérience</div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for @experience, defaults: {label:false} do |f| %>
  <%= f.input :title,
              placeholder: "Faire un road trip en combi..." %>
  <%= f.input :category,
              as: :select,
              collection: Experience::CATEGORIES,
              prompt: "Choisissez une catégorie" %>
  <%= f.input :picture %>
  <%= f.input :description,
              label: false,
              as: :text,
              placeholder: "Description" %>
  <%= f.input :address,
              label: false,
              placeholder: "Adresse" %>
  <%= f.input :start_date,
              label: false,
              placeholder: "Début",
              as: :string,
              input_html: {class: "datetime date-inline"} %>
  <%= f.input :end_date,
              label: false,
              placeholder: "Fin",
              as: :string,
              input_html: {class: "datetime date-inline"} %>
  <%= f.input :status,
              label: false,
              collection: [["A vivre", false], ["S'en souvenir",true]],
              as: :radio_buttons,
              item_wrapper_class: "inline white",
              checked: false %>
  <%= f.button :submit, "Créez", class: "ghost-btn ghost-btn-white" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="">
      <%= image_tag "logo.png" %>
    </a>

    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search for featured stuff">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <hr>
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>

app/views/shared/_selection_bar.html.erb
<div class="bar bar-container">
  <div class="icon-btn bar-link">
    <%= image_tag "heart.png", {class: "large-icon"} %>
    <div class="icon-btn-text large-text">Expériences à vivre</div>
  </div>
  <div class="icon-btn bar-link">
    <%= image_tag "check.png", {class: "large-icon bar-link"} %>
    <div class="icon-btn-text large-text">Expériences vécues</div>
  </div>
</div>

app/views/shared/_test.html.erb
<div class="card-admin" style="background-image: url(<%= experience.picture.url(:medium)%>);">
  <%= image_tag 'Woom_logo_white.png' , class: "card-admin-logo" %>
  <span class="card-admin-category bg-<%= experience.category.downcase %>">
    <%= experience.category.capitalize %>
  </span>
  <div class="card-admin-shadow"></div>
  <%= link_to admin_experience_path(experience) do %>
    <div class="card-admin-content">
      <h1><%= experience.title.capitalize %></h1>
      <%= link_to admin_user_path(experience.user) do %>
        <p>
          inspiré par <%= experience.user.first_name %>
          <% if experience.user.picture %>
            <%= image_tag experience.user.picture, class: "avatar" %>
          <% end %>
        </p>
      <% end %>
    </div>
  <% end %>
  <div class="card-admin-hashtag">#WOom<%= experience.category.capitalize%></div>
</div>

app/views/shared/_topbar.html.erb
<div class="topbar topbar-container topbar-absolute">
  <div class="topbar-logo">
    <%= link_to root_path do %>
      <%= image_tag "Woom_logo_white.png" %>
    <% end %>
  </div>
<!--   <div class="topbar-count">
      <%= image_tag "heart.png" %>5
      <%= image_tag "check.png" %>12
  </div> -->
  <% if user_signed_in? %>
  <div class="topbar-item">
    <div class="dropdown">
      <%= image_tag current_user.picture, class: "avatar dropdown-toggle", "data-toggle" => "dropdown" %>
      <ul class="dropdown-menu dropdown-menu-right topbar-dropdown-menu">
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
             <i class="fa fa-sign-out"></i> Déconnexion
          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <% else %>
    <div class="topbar-inline-menu">
      <ul class="list-inline">
        <li>
          <%= link_to "inscription", new_user_registration_path, class: "topbar-link" %>
        </li>
        <li><hr></li>
        <li>
          <%= link_to "connexion", new_user_session_path, class: "topbar-link" %>
        </li>
      </ul>
    </div>
  <% end %>
</div>

app/views/shared/test.html.erb
hello